apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: app
        version: "2.0.0"
        region: "uk-south"
    spec:
      containers:
      - name: application
        image: learnk8s/app:2.0.0
        ports:
          - containerPort: 8080

        readinessProbe:
          httpGet:
            path: /health
            port: 8080

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
